### ISSUE TITLE
Add content to 3. Running jobs on abel

### ISSUE THREAD

**Issue by lexnederbragt** [uio-cees/hpc-lessons#8]
- [ ] some theory: slurm scripts versus interactive jobs
- [ ] submitting a job to abel through a slurm script
- [ ] checking the status of a job
- [ ] cancelling a job
- [ ] interactive use of abel resources through `qlogin`

**Comment by Thomieh73** [comment]
Hi Lex,
I think this is done. I did not do it, but somebody else. I will close this issue.
